{{- if not .Values.secret.mysql.existSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zentao.fullname" . }}
  labels:
    {{- include "zentao.labels" . | nindent 4 }}
type: Opaque
data:
  zentao-mysql-root-password: {{ include "zentao.mysql.rootPassword" . | b64enc }}
{{- end -}}